from __future__ import annotations

"""Cross-version database upgrade, backup, and recovery rehearsal.

The bundled SQL fixture was generated by the sealed VulnFlow 48.0.0 release
(schema 35). This script materializes that database, upgrades it through the
current migration path, verifies retained records, and rehearses both raw
SQLite backup restore and signed recovery-bundle restore.
"""

import argparse
import gzip
import hashlib
import json
import shutil
import sqlite3
import sys
import tempfile
from pathlib import Path
from typing import Any

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.core.database_schema import (  # noqa: E402
    CURRENT_APP_VERSION,
    CURRENT_SCHEMA_VERSION,
    get_schema_info,
    init_db,
)
from app.repositories.finding_workflow import update_workflow  # noqa: E402
from app.repositories.findings import get_finding  # noqa: E402
from app.services.database_lifecycle import (  # noqa: E402
    backup_database,
    restore_database,
    validate_database_file,
)
from app.services.recovery import (  # noqa: E402
    create_recovery_bundle,
    restore_recovery_bundle,
    validate_recovery_bundle,
)

FIXTURE_DIR = ROOT / "tests" / "fixtures"
FIXTURE_ARCHIVE = FIXTURE_DIR / "v48_schema35.sqlite3.gz"
FIXTURE_META = FIXTURE_DIR / "v48_schema35_fixture.json"
SIGNING_KEY = "vulnflow-upgrade-rehearsal-signing-key"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def materialize_fixture(destination: Path) -> dict[str, Any]:
    metadata = json.loads(FIXTURE_META.read_text(encoding="utf-8"))
    if metadata.get("fixture_format") != "vulnflow-legacy-sqlite-gzip-fixture/1":
        raise ValueError("unsupported legacy fixture format")
    expected = str(metadata.get("compressed_database_sha256") or "")
    actual = _sha256(FIXTURE_ARCHIVE)
    if expected != actual:
        raise ValueError("legacy compressed fixture SHA-256 mismatch")
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        destination.unlink()
    with gzip.open(FIXTURE_ARCHIVE, "rb") as source, destination.open("wb") as target:
        shutil.copyfileobj(source, target)
    uncompressed = _sha256(destination)
    if uncompressed != str(metadata.get("uncompressed_database_sha256") or ""):
        raise ValueError("legacy database fixture SHA-256 mismatch")
    with sqlite3.connect(destination) as conn:
        schema = int(conn.execute("PRAGMA user_version").fetchone()[0])
        counts = {
            "findings": int(conn.execute("SELECT COUNT(*) FROM findings").fetchone()[0]),
            "campaigns": int(conn.execute("SELECT COUNT(*) FROM remediation_campaigns").fetchone()[0]),
            "background_jobs": int(conn.execute("SELECT COUNT(*) FROM background_jobs").fetchone()[0]),
        }
    return {"metadata": metadata, "schema_version": schema, "counts": counts, "sha256": uncompressed}


def _table_count(db_path: Path, table: str) -> int:
    with sqlite3.connect(db_path) as conn:
        return int(conn.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0])


def _job_payloads(db_path: Path) -> list[dict[str, Any]]:
    with sqlite3.connect(db_path) as conn:
        rows = conn.execute("SELECT job_type,status,payload_json FROM background_jobs ORDER BY created_at,job_id").fetchall()
    output = []
    for job_type, status, payload_json in rows:
        output.append({"job_type": job_type, "status": status, "payload": json.loads(payload_json or "{}")})
    return output


def run_rehearsal(work_dir: Path) -> dict[str, Any]:
    work_dir.mkdir(parents=True, exist_ok=True)
    legacy_db = work_dir / "legacy-v48-schema35.sqlite3"
    live_db = work_dir / "live-current.sqlite3"
    current_backup = work_dir / "current-backup.sqlite3"
    recovery_bundle = work_dir / "current-recovery.zip"
    recovered_db = work_dir / "recovered-current.sqlite3"

    checks: list[dict[str, Any]] = []

    def check(name: str, passed: bool, detail: Any) -> None:
        checks.append({"name": name, "passed": bool(passed), "detail": detail})
        if not passed:
            raise AssertionError(f"{name}: {detail}")

    fixture = materialize_fixture(legacy_db)
    meta = fixture["metadata"]
    check(
        "fixture provenance",
        meta.get("source_release") == "48.0.0" and meta.get("source_schema_version") == 35,
        {"source_release": meta.get("source_release"), "source_schema_version": meta.get("source_schema_version")},
    )
    check(
        "legacy fixture materialization",
        fixture["schema_version"] == 35 and fixture["counts"] == meta.get("contains"),
        {"schema_version": fixture["schema_version"], "counts": fixture["counts"]},
    )

    legacy_validation = validate_database_file(legacy_db)
    check(
        "legacy database compatibility validation",
        legacy_validation["schema_version"] == 35 and legacy_validation["finding_count"] == 2,
        legacy_validation,
    )
    audit_integrity = legacy_validation.get("audit_integrity") or {}
    check("legacy audit chain integrity", bool(audit_integrity.get("valid")), audit_integrity)

    init_db(live_db)
    restore_result = restore_database(live_db, legacy_db, actor="upgrade-rehearsal")
    safety_backup = Path(restore_result["safety_backup"])
    check("pre-restore safety backup", safety_backup.is_file() and safety_backup.stat().st_size > 0, safety_backup.name)

    schema = get_schema_info(live_db)
    migrated_versions = {int(item["version"]) for item in schema["migrations"]}
    check(
        "schema 35 to current migration",
        schema["schema_version"] == CURRENT_SCHEMA_VERSION
        and schema["app_version"] == CURRENT_APP_VERSION
        and set(range(36, CURRENT_SCHEMA_VERSION + 1)).issubset(migrated_versions),
        {"schema": schema["schema_version"], "app": schema["app_version"], "migrations": sorted(migrated_versions)},
    )

    first = get_finding(live_db, "LEGACY-001")
    second = get_finding(live_db, "LEGACY-002")
    check(
        "legacy findings preserved",
        bool(first and second)
        and first.get("owner") == "legacy-team"
        and second.get("status") == "IN_PROGRESS",
        {"legacy_001": first, "legacy_002": second},
    )
    jobs = _job_payloads(live_db)
    check(
        "legacy campaign and job preserved",
        _table_count(live_db, "remediation_campaigns") == 1
        and len(jobs) == 1
        and jobs[0]["job_type"] == "RESCORE_ALL"
        and jobs[0]["payload"].get("reason") == "legacy-upgrade-rehearsal",
        {"campaigns": _table_count(live_db, "remediation_campaigns"), "jobs": jobs},
    )

    backup_database(live_db, current_backup)
    backup_validation = validate_database_file(current_backup)
    check(
        "current backup validation",
        backup_validation["schema_version"] == CURRENT_SCHEMA_VERSION
        and backup_validation["finding_count"] == 2,
        backup_validation,
    )

    original = get_finding(live_db, "LEGACY-001") or {}
    update_workflow(
        live_db,
        "LEGACY-001",
        status=str(original.get("status") or "OPEN"),
        owner="mutated-after-backup",
        due_date=str(original.get("due_date") or ""),
        exception_expiry=str(original.get("exception_expiry") or ""),
        risk_acceptance_reason=str(original.get("risk_acceptance_reason") or ""),
        risk_acceptance_approver=str(original.get("risk_acceptance_approver") or ""),
        notes="mutation must be reverted",
        actor="upgrade-rehearsal",
    )
    restore_database(live_db, current_backup, actor="upgrade-rehearsal")
    reverted = get_finding(live_db, "LEGACY-001") or {}
    check(
        "current backup restore reverts mutation",
        reverted.get("owner") == "legacy-team" and "mutation must be reverted" not in str(reverted.get("notes") or ""),
        {"owner": reverted.get("owner"), "notes": reverted.get("notes")},
    )

    created = create_recovery_bundle(
        live_db,
        recovery_bundle,
        signing_key=SIGNING_KEY,
        created_by="upgrade-rehearsal",
        base_dir=ROOT,
    )
    validated = validate_recovery_bundle(
        recovery_bundle,
        signing_key=SIGNING_KEY,
        require_signature=True,
        current_schema_version=CURRENT_SCHEMA_VERSION,
    )
    check(
        "signed recovery bundle validation",
        bool(created.get("signed")) and bool(validated.get("valid")) and validated["database"]["finding_count"] == 2,
        {"signed": created.get("signed"), "valid": validated.get("valid"), "sha256": validated.get("bundle_sha256")},
    )

    restore_recovery_bundle(
        recovered_db,
        recovery_bundle,
        actor="upgrade-rehearsal",
        signing_key=SIGNING_KEY,
        require_signature=True,
        current_schema_version=CURRENT_SCHEMA_VERSION,
    )
    recovered_schema = get_schema_info(recovered_db)
    recovered_first = get_finding(recovered_db, "LEGACY-001")
    check(
        "recovery bundle restore equivalence",
        recovered_schema["schema_version"] == CURRENT_SCHEMA_VERSION
        and bool(recovered_first)
        and recovered_first.get("owner") == "legacy-team"
        and _table_count(recovered_db, "remediation_campaigns") == 1
        and _table_count(recovered_db, "background_jobs") == 1,
        {
            "schema": recovered_schema["schema_version"],
            "finding_owner": (recovered_first or {}).get("owner"),
            "campaigns": _table_count(recovered_db, "remediation_campaigns"),
            "jobs": _table_count(recovered_db, "background_jobs"),
        },
    )

    return {
        "format": "vulnflow-upgrade-restore-rehearsal/1",
        "source_release": meta["source_release"],
        "source_schema_version": meta["source_schema_version"],
        "target_release": CURRENT_APP_VERSION,
        "target_schema_version": CURRENT_SCHEMA_VERSION,
        "passed": all(item["passed"] for item in checks),
        "checks_passed": sum(1 for item in checks if item["passed"]),
        "checks_total": len(checks),
        "checks": checks,
        "artifacts": {
            "legacy_fixture_sha256": fixture["sha256"],
            "current_backup_sha256": _sha256(current_backup),
            "recovery_bundle_sha256": _sha256(recovery_bundle),
        },
    }


def _text_report(result: dict[str, Any]) -> str:
    lines = [
        f"VulnFlow {result['target_release']} cross-version upgrade and restore rehearsal",
        "",
        f"source_release: {result['source_release']}",
        f"source_schema_version: {result['source_schema_version']}",
        f"target_release: {result['target_release']}",
        f"target_schema_version: {result['target_schema_version']}",
        f"result: {result['checks_passed']}/{result['checks_total']}",
        "",
    ]
    for item in result["checks"]:
        lines.append(f"[{'PASS' if item['passed'] else 'FAIL'}] {item['name']}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--work-dir", type=Path)
    parser.add_argument("--json-output", type=Path)
    parser.add_argument("--text-output", type=Path)
    args = parser.parse_args()

    if args.work_dir:
        result = run_rehearsal(args.work_dir)
    else:
        with tempfile.TemporaryDirectory(prefix="vulnflow_upgrade_restore_") as name:
            result = run_rehearsal(Path(name))

    payload = json.dumps(result, ensure_ascii=False, sort_keys=True, indent=2) + "\n"
    text = _text_report(result)
    if args.json_output:
        args.json_output.parent.mkdir(parents=True, exist_ok=True)
        args.json_output.write_text(payload, encoding="utf-8")
    if args.text_output:
        args.text_output.parent.mkdir(parents=True, exist_ok=True)
        args.text_output.write_text(text, encoding="utf-8")
    print(text, end="")
    return 0 if result["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
