from __future__ import annotations

"""Stable compatibility order for application service exports."""

APPLICATION_SERVICE_NAMES = tuple(
    """
    build_scanner_compatibility_report build_scanner_collection_bundle CANONICAL_IMPORT_FIELDS create_preview_session delete_preview_session
    import_format_label load_preview_session map_import_rows parse_import_file
    authenticate_request authenticate_session authenticate_user_password count_active_users
    create_session create_user get_user hash_password
    list_users normalize_username prune_auth_records revoke_session
    revoke_user_sessions set_user_active set_user_password unlock_user
    validate_password verify_password accessible_projects create_project
    default_project get_project list_project_members list_projects
    normalize_project_name project_selection resolve_project set_project_membership
    set_project_status decorate_project_rows inspect_project_integrity latest_project_backup
    project_recovery_inventory project_recovery_mode has_role parse_api_tokens
    Metrics REQUEST_ID_RE configure_json_logging build_signing_config
    collect_signing_key_usage build_ed25519_signing_config ACTIVE_STATUSES ALLOWED_STATUSES
    as_bool exception_state is_overdue load_policy
    parse_policy_text policy_digest parse_date prioritize_finding
    CURRENT_APP_VERSION CURRENT_SCHEMA_VERSION get_schema_info init_coordination_db
    init_db ConcurrencyError utc_now add_asset_identifier
    analyze_asset_merge analyze_asset_merge_rollback apply_asset_inventory approve_asset_merge_request
    approve_asset_merge_rollback_request create_asset_merge_request create_asset_merge_rollback_request get_asset_identity_candidate
    get_asset_merge_request get_asset_merge_rollback_request list_asset_identifiers list_asset_identity_candidates
    list_asset_merge_history list_asset_merge_requests list_asset_merge_rollback_requests preflight_asset_merge_request
    reject_asset_identity_candidate reject_asset_merge_request reject_asset_merge_rollback_request get_asset
    list_assets list_exposure_groups add_audit_event create_audit_checkpoint
    list_audit_checkpoints list_audit_events list_audit_prune_history verify_audit_integrity
    add_campaign_findings create_campaign get_campaign list_campaigns
    remove_campaign_finding update_campaign_status acquire_cluster_lease active_cluster_lease
    begin_cluster_write_activity count_cluster_write_activities deregister_cluster_instance end_cluster_write_activity
    get_cluster_instance get_cluster_lease heartbeat_cluster_instance list_cluster_instances
    list_cluster_leases list_cluster_write_activities prune_stale_cluster_instances prune_stale_cluster_write_activities
    register_cluster_instance release_cluster_lease list_execution_receipt_archives count_execution_receipts
    get_execution_receipt list_execution_receipts replay_execution_receipt apply_import_batch
    bulk_update_intel bulk_update_workflow create_remediation_verification_request create_risk_approval_request
    decide_remediation_verification_request decide_risk_approval_request delete_all_findings get_source_reconciliation
    list_finding_observations list_import_batches list_reconciliation_findings list_remediation_verification_requests
    list_risk_approval_requests list_source_finding_records resolve_source_conflict retire_source_conflict_resolution
    update_record_state update_scores update_workflow upsert_findings
    count_findings get_finding list_findings get_pilot_profile
    save_pilot_profile IdempotencyConflict count_idempotency_records claim_background_job
    complete_background_job count_active_background_jobs create_background_job fail_background_job
    get_background_job heartbeat_background_job list_background_jobs purge_background_jobs
    request_background_job_cancel retry_background_job approve_policy_activation_request create_policy_activation_request
    create_policy_version get_active_policy_version get_policy_activation_request get_policy_version
    list_policy_activation_requests list_policy_versions reject_policy_activation_request count_pending_webhooks
    list_webhook_events retry_webhook_event backup_database list_maintenance_runs
    restore_database validate_database_file get_evidence_artifact list_evidence_artifacts
    resolve_evidence_path retire_evidence_artifact store_verification_evidence scan_evidence_artifact
    waive_evidence_scan evidence_download_allowed verify_evidence_artifact verify_evidence_store
    list_evidence_custody_events verify_evidence_custody_chain transfer_evidence_custody record_evidence_access
    IntelligenceError fetch_epss fetch_kev_catalog record_maintenance_failure
    run_maintenance database_health list_database_maintenance_runs run_database_maintenance
    generate_executive_html_report generate_html_report report_summary build_pilot_readiness
    finding_summary list_scanner_sources operational_counts query_findings
    create_findings_csv_export enforce_export_storage_budget expire_export_artifact export_storage_status
    get_export_artifact list_export_artifacts mark_export_artifact_corrupt purge_expired_export_artifacts
    reconcile_export_artifacts record_export_download resolve_export_artifact_path set_export_artifact_pinned
    stream_findings_csv verify_export_artifact create_integrity_proof_bundle verify_integrity_proof_bundle
    create_integrity_proof_key_transition export_integrity_proof_key_transitions list_integrity_proof_key_transitions create_integrity_proof_key_revocation
    export_integrity_proof_key_revocations list_integrity_proof_key_revocations create_integrity_proof_revocation_checkpoint export_integrity_proof_revocation_checkpoints
    list_integrity_proof_revocation_checkpoints create_integrity_proof_checkpoint_witness export_integrity_proof_checkpoint_witnesses list_integrity_proof_checkpoint_witnesses
    export_integrity_proof_transparency_entries export_integrity_proof_transparency_heads list_integrity_proof_transparency_entries list_integrity_proof_transparency_heads
    publish_integrity_proof_transparency_head create_integrity_proof_transparency_mirror_receipt export_integrity_proof_transparency_mirror_receipts list_integrity_proof_transparency_mirror_receipts
    create_integrity_proof_mirror_consistency_checkpoint export_integrity_proof_mirror_consistency_checkpoints list_integrity_proof_mirror_consistency_checkpoints build_config_audit
    create_recovery_bundle create_scheduled_recovery_bundle list_recovery_bundles restore_recovery_bundle
    external_project_backup_dir list_external_recovery_bundles list_local_recovery_bundles list_recovery_drills
    mirror_recovery_bundle resolve_stored_recovery_bundle run_recovery_drill validate_recovery_bundle
    create_baseline evaluate_drift list_baselines list_drift_checks
    record_drift_check change_control_counts create_change_request decide_change_request
    evaluate_change_control get_change_request list_change_requests promote_change_request
    SbomError VEX_JUSTIFICATIONS VEX_RESPONSES VEX_STATES
    compare_cyclonedx create_vex_revision decide_sbom_finding_link decide_vex_statement
    export_cyclonedx_vex get_sbom_document get_vex_statement list_sbom_documents
    list_vex_approval_requests parse_cyclonedx_json reconcile_sbom_findings request_vex_approval
    store_cyclonedx_document run_osv_scan list_osv_scans list_osv_matches
    decide_osv_match compare_policy_impact parse_and_describe_policy score_with_policy
    OsvError WebhookConfigError deliver_due_events parse_webhook_endpoints
    queue_event execute_background_job_for_context context_job_worker_loop LifecycleSupervisor
    context_backup_loop context_cluster_snapshot context_coordination_db_path context_coordination_loop
    context_coordination_tick context_instance_capabilities context_is_scheduler_leader context_maintenance_loop
    context_restore_in_progress context_webhook_loop WriteBarrierActive bind_operation_guard
    transaction_scope
    """.split()
)

__all__ = ["APPLICATION_SERVICE_NAMES"]
