from __future__ import annotations

"""Repositories application service exports."""

from app.service_registry.common import export_namespace
from app.repositories.asset_identity_writes import (
    add_asset_identifier,
    get_asset_identity_candidate,
    list_asset_identifiers,
    list_asset_identity_candidates,
    reject_asset_identity_candidate,
)
from app.repositories.asset_inventory import apply_asset_inventory
from app.repositories.asset_merge import (
    analyze_asset_merge,
    approve_asset_merge_request,
    create_asset_merge_request,
    get_asset_merge_request,
    list_asset_merge_history,
    list_asset_merge_requests,
    preflight_asset_merge_request,
    reject_asset_merge_request,
)
from app.repositories.asset_merge_rollback import (
    analyze_asset_merge_rollback,
    approve_asset_merge_rollback_request,
    create_asset_merge_rollback_request,
    get_asset_merge_rollback_request,
    list_asset_merge_rollback_requests,
    reject_asset_merge_rollback_request,
)
from app.repositories.assets import (
    get_asset,
    list_assets,
    list_exposure_groups,
)
from app.repositories.audit import (
    add_audit_event,
    create_audit_checkpoint,
    list_audit_checkpoints,
    list_audit_events,
    list_audit_prune_history,
    verify_audit_integrity,
)
from app.repositories.campaigns import (
    add_campaign_findings,
    create_campaign,
    get_campaign,
    list_campaigns,
    remove_campaign_finding,
    update_campaign_status,
)
from app.repositories.cluster import (
    acquire_cluster_lease,
    active_cluster_lease,
    begin_cluster_write_activity,
    count_cluster_write_activities,
    deregister_cluster_instance,
    end_cluster_write_activity,
    get_cluster_instance,
    get_cluster_lease,
    heartbeat_cluster_instance,
    list_cluster_instances,
    list_cluster_leases,
    list_cluster_write_activities,
    prune_stale_cluster_instances,
    prune_stale_cluster_write_activities,
    register_cluster_instance,
    release_cluster_lease,
)
from app.repositories.execution_receipt_retention import list_execution_receipt_archives
from app.repositories.execution_receipts import (
    count_execution_receipts,
    get_execution_receipt,
    list_execution_receipts,
    replay_execution_receipt,
)
from app.repositories.finding_approvals import (
    create_risk_approval_request,
    decide_risk_approval_request,
    list_risk_approval_requests,
)
from app.repositories.finding_ingestion import (
    apply_import_batch,
    get_source_reconciliation,
    list_import_batches,
    list_reconciliation_findings,
    list_source_finding_records,
    resolve_source_conflict,
    retire_source_conflict_resolution,
    update_scores,
    upsert_findings,
)
from app.repositories.finding_workflow import (
    bulk_update_intel,
    bulk_update_workflow,
    create_remediation_verification_request,
    decide_remediation_verification_request,
    delete_all_findings,
    list_finding_observations,
    list_remediation_verification_requests,
    update_record_state,
    update_workflow,
)
from app.repositories.findings import (
    count_findings,
    get_finding,
    list_findings,
)
from app.repositories.idempotency import (
    IdempotencyConflict,
    count_idempotency_records,
)
from app.repositories.job_execution import (
    claim_background_job,
    complete_background_job,
    fail_background_job,
    heartbeat_background_job,
)
from app.repositories.job_records import (
    count_active_background_jobs,
    create_background_job,
    get_background_job,
    list_background_jobs,
    purge_background_jobs,
    request_background_job_cancel,
    retry_background_job,
)
from app.repositories.pilot import (
    get_pilot_profile,
    save_pilot_profile,
)
from app.repositories.policies import (
    approve_policy_activation_request,
    create_policy_activation_request,
    create_policy_version,
    get_active_policy_version,
    get_policy_activation_request,
    get_policy_version,
    list_policy_activation_requests,
    list_policy_versions,
    reject_policy_activation_request,
)
from app.repositories.webhook_queue import (
    count_pending_webhooks,
    list_webhook_events,
    retry_webhook_event,
)

SERVICE_NAMES = (
    'add_asset_identifier',
    'analyze_asset_merge',
    'analyze_asset_merge_rollback',
    'apply_asset_inventory',
    'approve_asset_merge_request',
    'approve_asset_merge_rollback_request',
    'create_asset_merge_request',
    'create_asset_merge_rollback_request',
    'get_asset_identity_candidate',
    'get_asset_merge_request',
    'get_asset_merge_rollback_request',
    'list_asset_identifiers',
    'list_asset_identity_candidates',
    'list_asset_merge_history',
    'list_asset_merge_requests',
    'list_asset_merge_rollback_requests',
    'preflight_asset_merge_request',
    'reject_asset_identity_candidate',
    'reject_asset_merge_request',
    'reject_asset_merge_rollback_request',
    'get_asset',
    'list_assets',
    'list_exposure_groups',
    'add_audit_event',
    'create_audit_checkpoint',
    'list_audit_checkpoints',
    'list_audit_events',
    'list_audit_prune_history',
    'verify_audit_integrity',
    'add_campaign_findings',
    'create_campaign',
    'get_campaign',
    'list_campaigns',
    'remove_campaign_finding',
    'update_campaign_status',
    'acquire_cluster_lease',
    'active_cluster_lease',
    'begin_cluster_write_activity',
    'count_cluster_write_activities',
    'deregister_cluster_instance',
    'end_cluster_write_activity',
    'get_cluster_instance',
    'get_cluster_lease',
    'heartbeat_cluster_instance',
    'list_cluster_instances',
    'list_cluster_leases',
    'list_cluster_write_activities',
    'prune_stale_cluster_instances',
    'prune_stale_cluster_write_activities',
    'register_cluster_instance',
    'release_cluster_lease',
    'list_execution_receipt_archives',
    'count_execution_receipts',
    'get_execution_receipt',
    'list_execution_receipts',
    'replay_execution_receipt',
    'apply_import_batch',
    'bulk_update_intel',
    'bulk_update_workflow',
    'create_remediation_verification_request',
    'create_risk_approval_request',
    'decide_remediation_verification_request',
    'decide_risk_approval_request',
    'delete_all_findings',
    'get_source_reconciliation',
    'list_finding_observations',
    'list_import_batches',
    'list_reconciliation_findings',
    'list_remediation_verification_requests',
    'list_risk_approval_requests',
    'list_source_finding_records',
    'resolve_source_conflict',
    'retire_source_conflict_resolution',
    'update_record_state',
    'update_scores',
    'update_workflow',
    'upsert_findings',
    'count_findings',
    'get_finding',
    'list_findings',
    'get_pilot_profile',
    'save_pilot_profile',
    'IdempotencyConflict',
    'count_idempotency_records',
    'claim_background_job',
    'complete_background_job',
    'count_active_background_jobs',
    'create_background_job',
    'fail_background_job',
    'get_background_job',
    'heartbeat_background_job',
    'list_background_jobs',
    'purge_background_jobs',
    'request_background_job_cancel',
    'retry_background_job',
    'approve_policy_activation_request',
    'create_policy_activation_request',
    'create_policy_version',
    'get_active_policy_version',
    'get_policy_activation_request',
    'get_policy_version',
    'list_policy_activation_requests',
    'list_policy_versions',
    'reject_policy_activation_request',
    'count_pending_webhooks',
    'list_webhook_events',
    'retry_webhook_event',
)
SERVICE_EXPORTS = export_namespace(globals(), SERVICE_NAMES)

__all__ = ["SERVICE_EXPORTS", "SERVICE_NAMES"]
