from __future__ import annotations

"""Environment-derived runtime settings.

The web module re-exports these names for backward-compatible tests and local
operators, while parsing and defaults live in one reviewable module.
"""

import os
import re
import secrets
import socket
import uuid
from pathlib import Path

from app.services.osv import validate_api_base
APP_DIR = Path(__file__).resolve().parents[1]
BASE_DIR = Path(os.getenv("VULNFLOW_BASE_DIR", APP_DIR.parent))
DATA_DIR = Path(os.getenv("VULNFLOW_DATA_DIR", BASE_DIR / "data"))
PROJECTS_DIR = Path(os.getenv("VULNFLOW_PROJECTS_DIR", DATA_DIR / "projects"))
LEGACY_DB_PATH = Path(os.getenv("VULNFLOW_DB", DATA_DIR / "vulnflow.db"))
CONTROL_DB_PATH = Path(os.getenv("VULNFLOW_CONTROL_DB", DATA_DIR / "control.db"))
DEFAULT_PROJECT_ROOT = Path(os.getenv("VULNFLOW_DEFAULT_PROJECT_ROOT", PROJECTS_DIR / "default"))
DEFAULT_PROJECT_DB_PATH = Path(
    os.getenv("VULNFLOW_DEFAULT_PROJECT_DB", DEFAULT_PROJECT_ROOT / "vulnflow.db")
)
DB_PATH = DEFAULT_PROJECT_DB_PATH
PROJECT_COOKIE = os.getenv("VULNFLOW_PROJECT_COOKIE", "vulnflow_project")
_SOURCE_POLICY_PATH = BASE_DIR / "rules" / "prioritization_policy.yml"
_PACKAGED_POLICY_PATH = APP_DIR / "resources" / "prioritization_policy.yml"
POLICY_PATH = Path(os.getenv("VULNFLOW_POLICY", _SOURCE_POLICY_PATH if _SOURCE_POLICY_PATH.exists() else _PACKAGED_POLICY_PATH))
_SOURCE_SAMPLE_PATH = DATA_DIR / "sample_findings.csv"
_PACKAGED_SAMPLE_PATH = APP_DIR / "static" / "sample_findings.csv"
SAMPLE_PATH = Path(os.getenv("VULNFLOW_SAMPLE_PATH", _SOURCE_SAMPLE_PATH if _SOURCE_SAMPLE_PATH.exists() else _PACKAGED_SAMPLE_PATH))
MAX_UPLOAD_BYTES = 5 * 1024 * 1024
MAX_IMPORT_UPLOAD_BYTES = max(1024 * 1024, min(100 * 1024 * 1024, int(os.getenv("VULNFLOW_IMPORT_MAX_BYTES", str(20 * 1024 * 1024)) or (20 * 1024 * 1024))))
IMPORT_PREVIEW_TTL_SECONDS = max(300, min(86400, int(os.getenv("VULNFLOW_IMPORT_PREVIEW_TTL_SECONDS", "1800") or 1800)))
IMPORT_PREVIEW_DIR = Path(os.getenv("VULNFLOW_IMPORT_PREVIEW_DIR", DEFAULT_PROJECT_ROOT / "import-previews"))
MAX_BACKUP_BYTES = 50 * 1024 * 1024
MAX_RECOVERY_BUNDLE_BYTES = 250 * 1024 * 1024
MAX_EVIDENCE_BYTES = max(1024, int(os.getenv("VULNFLOW_EVIDENCE_MAX_BYTES", str(10 * 1024 * 1024)) or (10 * 1024 * 1024)))
EVIDENCE_SCANNER_MODE = os.getenv("VULNFLOW_EVIDENCE_SCANNER_MODE", "builtin").strip().lower()
EVIDENCE_CLAMSCAN_PATH = os.getenv("VULNFLOW_CLAMSCAN_PATH", "clamscan").strip() or "clamscan"
EVIDENCE_SCAN_TIMEOUT_SECONDS = max(1, int(os.getenv("VULNFLOW_EVIDENCE_SCAN_TIMEOUT_SECONDS", "30") or 30))
EVIDENCE_REQUIRE_CLEAN = os.getenv("VULNFLOW_EVIDENCE_REQUIRE_CLEAN", "1").strip().lower() in {"1","true","yes"}
OSV_API_BASE = validate_api_base(os.getenv("VULNFLOW_OSV_API_BASE", "https://api.osv.dev"))
OSV_TIMEOUT_SECONDS = max(1, int(os.getenv("VULNFLOW_OSV_TIMEOUT_SECONDS", "15") or 15))
OSV_RETRIES = max(1, min(5, int(os.getenv("VULNFLOW_OSV_RETRIES", "3") or 3)))
OSV_BATCH_SIZE = max(1, min(200, int(os.getenv("VULNFLOW_OSV_BATCH_SIZE", "100") or 100)))
OSV_MAX_RESPONSE_BYTES = max(4096, min(20 * 1024 * 1024, int(os.getenv("VULNFLOW_OSV_MAX_RESPONSE_BYTES", str(4 * 1024 * 1024)) or (4 * 1024 * 1024))))
INTEL_TIMEOUT_SECONDS = max(1, int(os.getenv("VULNFLOW_INTEL_TIMEOUT_SECONDS", "30") or 30))
INTEL_RETRIES = max(1, min(5, int(os.getenv("VULNFLOW_INTEL_RETRIES", "3") or 3)))
INTEL_MAX_RESPONSE_BYTES = max(4096, min(20 * 1024 * 1024, int(os.getenv("VULNFLOW_INTEL_MAX_RESPONSE_BYTES", str(8 * 1024 * 1024)) or (8 * 1024 * 1024))))
MAX_BULK_ITEMS = 500
MAX_CSV_ROWS = 5000
MAX_TEXT = 500
MAX_NOTES = 4000
MAX_REASON = 1500
MAX_POLICY_BYTES = 256 * 1024
CVE_RE = re.compile(r"^CVE-\d{4}-\d{4,}$", re.IGNORECASE)
CSRF_COOKIE = "vulnflow_csrf"
AUTH_USER = os.getenv("VULNFLOW_AUTH_USER", "").strip()
AUTH_PASSWORD = os.getenv("VULNFLOW_AUTH_PASSWORD", "")
AUTH_USERS_JSON = os.getenv("VULNFLOW_USERS_JSON", "")
AUTH_API_TOKENS_JSON = os.getenv("VULNFLOW_API_TOKENS_JSON", "")
AUTH_SESSION_COOKIE = os.getenv("VULNFLOW_AUTH_SESSION_COOKIE", "vulnflow_session").strip() or "vulnflow_session"
AUTH_SESSION_MINUTES = max(15, min(10080, int(os.getenv("VULNFLOW_AUTH_SESSION_MINUTES", "480") or 480)))
AUTH_SESSION_IDLE_MINUTES = max(0, min(AUTH_SESSION_MINUTES, int(os.getenv("VULNFLOW_AUTH_SESSION_IDLE_MINUTES", "0") or 0)))
AUTH_SESSION_BINDING = os.getenv("VULNFLOW_AUTH_SESSION_BINDING", "off").strip().lower() or "off"
if AUTH_SESSION_BINDING not in {"off", "user-agent", "strict"}:
    raise ValueError("VULNFLOW_AUTH_SESSION_BINDING은 off, user-agent, strict 중 하나여야 합니다.")
AUTH_MAX_ACTIVE_SESSIONS = max(1, min(50, int(os.getenv("VULNFLOW_AUTH_MAX_ACTIVE_SESSIONS", "10") or 10)))
AUTH_RATE_WINDOW_SECONDS = max(30, min(86400, int(os.getenv("VULNFLOW_AUTH_RATE_WINDOW_SECONDS", "300") or 300)))
AUTH_RATE_USERNAME_CLIENT_ATTEMPTS = max(3, min(100, int(os.getenv("VULNFLOW_AUTH_RATE_USERNAME_CLIENT_ATTEMPTS", "5") or 5)))
AUTH_RATE_CLIENT_ATTEMPTS = max(3, min(1000, int(os.getenv("VULNFLOW_AUTH_RATE_CLIENT_ATTEMPTS", "25") or 25)))
# Deprecated aliases retained for configuration compatibility. Account-wide lockout is disabled.
AUTH_LOCK_THRESHOLD = AUTH_RATE_USERNAME_CLIENT_ATTEMPTS
AUTH_LOCK_MINUTES = max(1, AUTH_RATE_WINDOW_SECONDS // 60)
DEMO_MODE = os.getenv("VULNFLOW_DEMO_MODE", "0").strip().lower() in {"1", "true", "yes"}
ALLOW_LOCAL_ADMIN_FALLBACK = os.getenv("VULNFLOW_ALLOW_LOCAL_ADMIN_FALLBACK", "0").strip().lower() in {"1", "true", "yes"}
WEBHOOKS_JSON = os.getenv("VULNFLOW_WEBHOOKS_JSON", "")
WEBHOOK_INTERVAL_SECONDS = max(0, int(os.getenv("VULNFLOW_WEBHOOK_INTERVAL_SECONDS", "15") or 15))
WEBHOOK_TIMEOUT_SECONDS = max(1, int(os.getenv("VULNFLOW_WEBHOOK_TIMEOUT_SECONDS", "10") or 10))
WEBHOOK_MAX_ATTEMPTS = max(1, int(os.getenv("VULNFLOW_WEBHOOK_MAX_ATTEMPTS", "5") or 5))
WEBHOOK_ALLOW_INSECURE_HTTP = os.getenv("VULNFLOW_WEBHOOK_ALLOW_INSECURE_HTTP", "0").strip().lower() in {"1", "true", "yes"}
OUTBOUND_ALLOW_PRIVATE_NETWORKS = os.getenv("VULNFLOW_OUTBOUND_ALLOW_PRIVATE_NETWORKS", "0").strip().lower() in {"1", "true", "yes"}
OUTBOUND_HOST_ALLOWLIST = os.getenv("VULNFLOW_OUTBOUND_HOST_ALLOWLIST", "").strip()
OUTBOUND_MAX_RESPONSE_BYTES = max(4096, min(10 * 1024 * 1024, int(os.getenv("VULNFLOW_OUTBOUND_MAX_RESPONSE_BYTES", str(1024 * 1024)) or (1024 * 1024))))
SMTP_ALLOW_PRIVATE_NETWORKS = os.getenv("VULNFLOW_SMTP_ALLOW_PRIVATE_NETWORKS", "0").strip().lower() in {"1", "true", "yes"}
SMTP_HOST_ALLOWLIST = os.getenv("VULNFLOW_SMTP_HOST_ALLOWLIST", "").strip()
SMTP_ALLOW_PLAIN = os.getenv("VULNFLOW_SMTP_ALLOW_PLAIN", "0").strip().lower() in {"1", "true", "yes"}
INTEGRATION_SECRET_KEY = os.getenv("VULNFLOW_INTEGRATION_SECRET_KEY", "")
COLLABORATION_INTERVAL_SECONDS = max(5, int(os.getenv("VULNFLOW_COLLABORATION_INTERVAL_SECONDS", "30") or 30))
COLLABORATION_TIMEOUT_SECONDS = max(1, int(os.getenv("VULNFLOW_COLLABORATION_TIMEOUT_SECONDS", "10") or 10))
COLLABORATION_MAX_ATTEMPTS = max(1, int(os.getenv("VULNFLOW_COLLABORATION_MAX_ATTEMPTS", "5") or 5))
COLLABORATION_DUE_SOON_DAYS = max(0, min(30, int(os.getenv("VULNFLOW_COLLABORATION_DUE_SOON_DAYS", "3") or 3)))
PUBLIC_BASE_URL = os.getenv("VULNFLOW_PUBLIC_BASE_URL", "").strip().rstrip("/")
SECURITY_PROFILE = os.getenv("VULNFLOW_SECURITY_PROFILE", "development").strip().lower() or "development"
if SECURITY_PROFILE not in {"development", "pilot", "production"}:
    raise ValueError("VULNFLOW_SECURITY_PROFILE은 development, pilot, production 중 하나여야 합니다.")
RUNTIME_DEPENDENCY_POLICY = os.getenv("VULNFLOW_RUNTIME_DEPENDENCY_POLICY", "off").strip().lower() or "off"
if RUNTIME_DEPENDENCY_POLICY not in {"off", "warn", "enforce"}:
    raise ValueError("VULNFLOW_RUNTIME_DEPENDENCY_POLICY는 off, warn, enforce 중 하나여야 합니다.")
LOG_LEVEL = os.getenv("VULNFLOW_LOG_LEVEL", "INFO")
MAINTENANCE_INTERVAL_MINUTES = max(0, int(os.getenv("VULNFLOW_MAINTENANCE_INTERVAL_MINUTES", "0") or 0))
AUDIT_RETENTION_DAYS = max(0, int(os.getenv("VULNFLOW_AUDIT_RETENTION_DAYS", "0") or 0))
IMPORT_RETENTION_DAYS = max(0, int(os.getenv("VULNFLOW_IMPORT_RETENTION_DAYS", "0") or 0))
AUTO_ARCHIVE_STALE_DAYS = max(0, int(os.getenv("VULNFLOW_AUTO_ARCHIVE_STALE_DAYS", "0") or 0))
VERIFICATION_ABSENCE_SCANS = max(1, int(os.getenv("VULNFLOW_VERIFICATION_ABSENCE_SCANS", "2") or 2))
WEBHOOK_RETENTION_DAYS = max(0, int(os.getenv("VULNFLOW_WEBHOOK_RETENTION_DAYS", "0") or 0))
JOB_WORKER_ENABLED = os.getenv("VULNFLOW_JOB_WORKER_ENABLED", "1").strip().lower() in {"1", "true", "yes"}
JOB_WORKER_INTERVAL_SECONDS = max(1, int(os.getenv("VULNFLOW_JOB_WORKER_INTERVAL_SECONDS", "2") or 2))
JOB_LEASE_SECONDS = max(15, int(os.getenv("VULNFLOW_JOB_LEASE_SECONDS", "120") or 120))
JOB_MAX_ATTEMPTS = max(1, int(os.getenv("VULNFLOW_JOB_MAX_ATTEMPTS", "3") or 3))
JOB_RETENTION_DAYS = max(0, int(os.getenv("VULNFLOW_JOB_RETENTION_DAYS", "30") or 30))
LIFECYCLE_SHUTDOWN_TIMEOUT_SECONDS = max(0.1, min(60.0, float(os.getenv("VULNFLOW_LIFECYCLE_SHUTDOWN_TIMEOUT_SECONDS", "5") or 5)))
IDEMPOTENCY_RETENTION_DAYS = max(1, min(365, int(os.getenv("VULNFLOW_IDEMPOTENCY_RETENTION_DAYS", "30") or 30)))
EXECUTION_RECEIPT_RETENTION_DAYS = max(
    0,
    min(3650, int(os.getenv("VULNFLOW_EXECUTION_RECEIPT_RETENTION_DAYS", "180") or 180)),
)
DB_WAL_WARN_BYTES = max(0, int(float(os.getenv("VULNFLOW_DB_WAL_WARN_MB", "128") or 0) * 1024 * 1024))
DB_RECLAIM_WARN_RATIO = max(0.0, min(1.0, float(os.getenv("VULNFLOW_DB_RECLAIM_WARN_RATIO", "0.20") or 0.20)))
BACKUP_INTERVAL_HOURS = max(0, int(os.getenv("VULNFLOW_BACKUP_INTERVAL_HOURS", "0") or 0))
BACKUP_RETENTION_COUNT = max(1, int(os.getenv("VULNFLOW_BACKUP_RETENTION_COUNT", "10") or 10))
_EXTERNAL_BACKUP_DIR_RAW = os.getenv("VULNFLOW_EXTERNAL_BACKUP_DIR", "").strip()
EXTERNAL_BACKUP_DIR = Path(_EXTERNAL_BACKUP_DIR_RAW).expanduser() if _EXTERNAL_BACKUP_DIR_RAW else None
EXTERNAL_BACKUP_RETENTION_COUNT = max(
    1,
    int(os.getenv("VULNFLOW_EXTERNAL_BACKUP_RETENTION_COUNT", "30") or 30),
)
SIGNING_KEYS_JSON = os.getenv("VULNFLOW_SIGNING_KEYS_JSON", "")
AUDIT_ACTIVE_KEY_ID = os.getenv("VULNFLOW_AUDIT_ACTIVE_KEY_ID", "").strip()
BACKUP_ACTIVE_KEY_ID = os.getenv("VULNFLOW_BACKUP_ACTIVE_KEY_ID", "").strip()
BACKUP_SIGNING_KEY = os.getenv("VULNFLOW_BACKUP_SIGNING_KEY", "")
BACKUP_REQUIRE_SIGNATURE = os.getenv("VULNFLOW_BACKUP_REQUIRE_SIGNATURE", "0").strip().lower() in {"1", "true", "yes"}
AUDIT_SIGNING_KEY = os.getenv("VULNFLOW_AUDIT_SIGNING_KEY", "")
_CURSOR_SIGNING_KEY_RAW = os.getenv("VULNFLOW_CURSOR_SIGNING_KEY", "").strip()
CURSOR_SIGNING_KEY = (_CURSOR_SIGNING_KEY_RAW or BACKUP_SIGNING_KEY or AUDIT_SIGNING_KEY or secrets.token_urlsafe(32))
CURSOR_SIGNING_KEY_CONFIGURED = bool(_CURSOR_SIGNING_KEY_RAW)
AUDIT_REQUIRE_SIGNATURE = os.getenv("VULNFLOW_AUDIT_REQUIRE_SIGNATURE", "0").strip().lower() in {"1", "true", "yes"}
INTEGRITY_PROOF_PRIVATE_KEYS_JSON = os.getenv("VULNFLOW_INTEGRITY_PROOF_PRIVATE_KEYS_JSON", "")
INTEGRITY_PROOF_PUBLIC_KEYS_JSON = os.getenv("VULNFLOW_INTEGRITY_PROOF_PUBLIC_KEYS_JSON", "")
INTEGRITY_PROOF_ACTIVE_KEY_ID = os.getenv("VULNFLOW_INTEGRITY_PROOF_ACTIVE_KEY_ID", "").strip()
INTEGRITY_PROOF_REQUIRE_PUBLIC_SIGNATURE = os.getenv("VULNFLOW_INTEGRITY_PROOF_REQUIRE_PUBLIC_SIGNATURE", "0").strip().lower() in {"1", "true", "yes"}
INTEGRITY_WITNESS_PRIVATE_KEYS_JSON = os.getenv("VULNFLOW_INTEGRITY_WITNESS_PRIVATE_KEYS_JSON", "")
INTEGRITY_WITNESS_PUBLIC_KEYS_JSON = os.getenv("VULNFLOW_INTEGRITY_WITNESS_PUBLIC_KEYS_JSON", "")
INTEGRITY_WITNESS_ACTIVE_KEY_ID = os.getenv("VULNFLOW_INTEGRITY_WITNESS_ACTIVE_KEY_ID", "").strip()
INTEGRITY_WITNESS_MIN_QUORUM = max(1, min(32, int(os.getenv("VULNFLOW_INTEGRITY_WITNESS_MIN_QUORUM", "1") or 1)))
INTEGRITY_TRANSPARENCY_PRIVATE_KEYS_JSON = os.getenv("VULNFLOW_INTEGRITY_TRANSPARENCY_PRIVATE_KEYS_JSON", "")
INTEGRITY_TRANSPARENCY_PUBLIC_KEYS_JSON = os.getenv("VULNFLOW_INTEGRITY_TRANSPARENCY_PUBLIC_KEYS_JSON", "")
INTEGRITY_TRANSPARENCY_ACTIVE_KEY_ID = os.getenv("VULNFLOW_INTEGRITY_TRANSPARENCY_ACTIVE_KEY_ID", "").strip()
INTEGRITY_TRANSPARENCY_REQUIRE_LOG = os.getenv("VULNFLOW_INTEGRITY_TRANSPARENCY_REQUIRE_LOG", "0").strip().lower() in {"1", "true", "yes"}
INTEGRITY_MIRROR_PRIVATE_KEYS_JSON = os.getenv("VULNFLOW_INTEGRITY_MIRROR_PRIVATE_KEYS_JSON", "")
INTEGRITY_MIRROR_PUBLIC_KEYS_JSON = os.getenv("VULNFLOW_INTEGRITY_MIRROR_PUBLIC_KEYS_JSON", "")
INTEGRITY_MIRROR_ACTIVE_KEY_ID = os.getenv("VULNFLOW_INTEGRITY_MIRROR_ACTIVE_KEY_ID", "").strip()
INTEGRITY_MIRROR_MIN_QUORUM = max(1, min(32, int(os.getenv("VULNFLOW_INTEGRITY_MIRROR_MIN_QUORUM", "1") or 1)))
INTEGRITY_MIRROR_REQUIRE_GOSSIP = os.getenv("VULNFLOW_INTEGRITY_MIRROR_REQUIRE_GOSSIP", "0").strip().lower() in {"1", "true", "yes"}
INTEGRITY_MIRROR_REQUIRE_CONSISTENCY = os.getenv("VULNFLOW_INTEGRITY_MIRROR_REQUIRE_CONSISTENCY", "0").strip().lower() in {"1", "true", "yes"}
RECOVERY_DIR = Path(os.getenv("VULNFLOW_RECOVERY_DIR", DEFAULT_PROJECT_ROOT / "backups" / "recovery"))
EVIDENCE_DIR = Path(os.getenv("VULNFLOW_EVIDENCE_DIR", DEFAULT_PROJECT_ROOT / "evidence"))
EXPORT_DIR = Path(os.getenv("VULNFLOW_EXPORT_DIR", DEFAULT_PROJECT_ROOT / "exports"))
LEGACY_EVIDENCE_DIR = DATA_DIR / "evidence"
LEGACY_EXPORT_DIR = DATA_DIR / "exports"
LEGACY_IMPORT_PREVIEW_DIR = DATA_DIR / "import-previews"
LEGACY_RECOVERY_DIR = DATA_DIR / "backups" / "recovery"
EXPORT_RETENTION_DAYS = max(0, int(os.getenv("VULNFLOW_EXPORT_RETENTION_DAYS", "7") or 7))
EXPORT_QUOTA_BYTES = max(0, int(float(os.getenv("VULNFLOW_EXPORT_QUOTA_MB", "1024") or 0) * 1024 * 1024))
EXPORT_MIN_FREE_BYTES = max(0, int(float(os.getenv("VULNFLOW_EXPORT_MIN_FREE_MB", "256") or 0) * 1024 * 1024))
COORDINATION_DB_ENV = os.getenv("VULNFLOW_COORDINATION_DB", "").strip()
CLUSTER_COORDINATION_ENABLED = os.getenv("VULNFLOW_CLUSTER_COORDINATION_ENABLED", "1").strip().lower() in {"1", "true", "yes"}
INSTANCE_HEARTBEAT_SECONDS = max(2, int(os.getenv("VULNFLOW_INSTANCE_HEARTBEAT_SECONDS", "10") or 10))
INSTANCE_TTL_SECONDS = max(INSTANCE_HEARTBEAT_SECONDS * 2, int(os.getenv("VULNFLOW_INSTANCE_TTL_SECONDS", "30") or 30))
SCHEDULER_LEASE_SECONDS = max(INSTANCE_HEARTBEAT_SECONDS * 2, int(os.getenv("VULNFLOW_SCHEDULER_LEASE_SECONDS", "30") or 30))
EXCLUSIVE_OPERATION_LEASE_SECONDS = max(60, int(os.getenv("VULNFLOW_EXCLUSIVE_OPERATION_LEASE_SECONDS", "300") or 300))
WRITE_ACTIVITY_TTL_SECONDS = max(60, int(os.getenv("VULNFLOW_WRITE_ACTIVITY_TTL_SECONDS", "600") or 600))
INSTANCE_ID = (os.getenv("VULNFLOW_INSTANCE_ID", "").strip() or f"{socket.gethostname()}-{os.getpid()}-{uuid.uuid4().hex[:8]}")
COOKIE_SECURE = os.getenv("VULNFLOW_COOKIE_SECURE", "0").strip().lower() in {"1", "true", "yes"}
SCHEDULER_LEASE_NAME = "scheduler:singleton"
RESTORE_LEASE_NAME = "exclusive:restore"
POLICY_ACTIVATION_LEASE_NAME = "exclusive:policy-activation"

__all__ = [
    'BASE_DIR',
    'APP_DIR',
    'DATA_DIR',
    'LEGACY_DB_PATH',
    'CONTROL_DB_PATH',
    'DEFAULT_PROJECT_ROOT',
    'DEFAULT_PROJECT_DB_PATH',
    'PROJECTS_DIR',
    'PROJECT_COOKIE',
    'DB_PATH',
    'POLICY_PATH',
    'SAMPLE_PATH',
    'MAX_UPLOAD_BYTES',
    'MAX_IMPORT_UPLOAD_BYTES',
    'IMPORT_PREVIEW_TTL_SECONDS',
    'IMPORT_PREVIEW_DIR',
    'MAX_BACKUP_BYTES',
    'MAX_RECOVERY_BUNDLE_BYTES',
    'MAX_EVIDENCE_BYTES',
    'EVIDENCE_SCANNER_MODE',
    'EVIDENCE_CLAMSCAN_PATH',
    'EVIDENCE_SCAN_TIMEOUT_SECONDS',
    'EVIDENCE_REQUIRE_CLEAN',
    'OSV_API_BASE',
    'OSV_TIMEOUT_SECONDS',
    'OSV_RETRIES',
    'OSV_BATCH_SIZE',
    'OSV_MAX_RESPONSE_BYTES',
    'INTEL_TIMEOUT_SECONDS',
    'INTEL_RETRIES',
    'INTEL_MAX_RESPONSE_BYTES',
    'MAX_BULK_ITEMS',
    'MAX_CSV_ROWS',
    'MAX_TEXT',
    'MAX_NOTES',
    'MAX_REASON',
    'MAX_POLICY_BYTES',
    'CVE_RE',
    'CSRF_COOKIE',
    'AUTH_USER',
    'AUTH_PASSWORD',
    'AUTH_USERS_JSON',
    'AUTH_API_TOKENS_JSON',
    'AUTH_SESSION_COOKIE',
    'AUTH_SESSION_MINUTES',
    'AUTH_SESSION_IDLE_MINUTES',
    'AUTH_SESSION_BINDING',
    'AUTH_MAX_ACTIVE_SESSIONS',
    'AUTH_RATE_WINDOW_SECONDS',
    'AUTH_RATE_USERNAME_CLIENT_ATTEMPTS',
    'AUTH_RATE_CLIENT_ATTEMPTS',
    'AUTH_LOCK_THRESHOLD',
    'AUTH_LOCK_MINUTES',
    'DEMO_MODE',
    'ALLOW_LOCAL_ADMIN_FALLBACK',
    'WEBHOOKS_JSON',
    'WEBHOOK_INTERVAL_SECONDS',
    'WEBHOOK_TIMEOUT_SECONDS',
    'WEBHOOK_MAX_ATTEMPTS',
    'WEBHOOK_ALLOW_INSECURE_HTTP',
    'OUTBOUND_ALLOW_PRIVATE_NETWORKS',
    'OUTBOUND_HOST_ALLOWLIST',
    'OUTBOUND_MAX_RESPONSE_BYTES',
    'SMTP_ALLOW_PRIVATE_NETWORKS',
    'SMTP_HOST_ALLOWLIST',
    'SMTP_ALLOW_PLAIN',
    'INTEGRATION_SECRET_KEY',
    'COLLABORATION_INTERVAL_SECONDS',
    'COLLABORATION_TIMEOUT_SECONDS',
    'COLLABORATION_MAX_ATTEMPTS',
    'COLLABORATION_DUE_SOON_DAYS',
    'PUBLIC_BASE_URL',
    'SECURITY_PROFILE',
    'RUNTIME_DEPENDENCY_POLICY',
    'LOG_LEVEL',
    'MAINTENANCE_INTERVAL_MINUTES',
    'AUDIT_RETENTION_DAYS',
    'IMPORT_RETENTION_DAYS',
    'AUTO_ARCHIVE_STALE_DAYS',
    'VERIFICATION_ABSENCE_SCANS',
    'WEBHOOK_RETENTION_DAYS',
    'JOB_WORKER_ENABLED',
    'JOB_WORKER_INTERVAL_SECONDS',
    'JOB_LEASE_SECONDS',
    'JOB_MAX_ATTEMPTS',
    'JOB_RETENTION_DAYS',
    'LIFECYCLE_SHUTDOWN_TIMEOUT_SECONDS',
    'IDEMPOTENCY_RETENTION_DAYS',
    'EXECUTION_RECEIPT_RETENTION_DAYS',
    'DB_WAL_WARN_BYTES',
    'DB_RECLAIM_WARN_RATIO',
    'BACKUP_INTERVAL_HOURS',
    'BACKUP_RETENTION_COUNT',
    'EXTERNAL_BACKUP_DIR',
    'EXTERNAL_BACKUP_RETENTION_COUNT',
    'SIGNING_KEYS_JSON',
    'AUDIT_ACTIVE_KEY_ID',
    'BACKUP_ACTIVE_KEY_ID',
    'BACKUP_SIGNING_KEY',
    'BACKUP_REQUIRE_SIGNATURE',
    'AUDIT_SIGNING_KEY',
    'CURSOR_SIGNING_KEY',
    'CURSOR_SIGNING_KEY_CONFIGURED',
    'AUDIT_REQUIRE_SIGNATURE',
    'INTEGRITY_PROOF_PRIVATE_KEYS_JSON',
    'INTEGRITY_PROOF_PUBLIC_KEYS_JSON',
    'INTEGRITY_PROOF_ACTIVE_KEY_ID',
    'INTEGRITY_PROOF_REQUIRE_PUBLIC_SIGNATURE',
    'INTEGRITY_WITNESS_PRIVATE_KEYS_JSON',
    'INTEGRITY_WITNESS_PUBLIC_KEYS_JSON',
    'INTEGRITY_WITNESS_ACTIVE_KEY_ID',
    'INTEGRITY_WITNESS_MIN_QUORUM',
    'INTEGRITY_TRANSPARENCY_PRIVATE_KEYS_JSON',
    'INTEGRITY_TRANSPARENCY_PUBLIC_KEYS_JSON',
    'INTEGRITY_TRANSPARENCY_ACTIVE_KEY_ID',
    'INTEGRITY_TRANSPARENCY_REQUIRE_LOG',
    'INTEGRITY_MIRROR_PRIVATE_KEYS_JSON',
    'INTEGRITY_MIRROR_PUBLIC_KEYS_JSON',
    'INTEGRITY_MIRROR_ACTIVE_KEY_ID',
    'INTEGRITY_MIRROR_MIN_QUORUM',
    'INTEGRITY_MIRROR_REQUIRE_GOSSIP',
    'INTEGRITY_MIRROR_REQUIRE_CONSISTENCY',
    'RECOVERY_DIR',
    'EVIDENCE_DIR',
    'EXPORT_DIR',
    'LEGACY_EVIDENCE_DIR',
    'LEGACY_EXPORT_DIR',
    'LEGACY_IMPORT_PREVIEW_DIR',
    'LEGACY_RECOVERY_DIR',
    'EXPORT_RETENTION_DAYS',
    'EXPORT_QUOTA_BYTES',
    'EXPORT_MIN_FREE_BYTES',
    'COORDINATION_DB_ENV',
    'CLUSTER_COORDINATION_ENABLED',
    'INSTANCE_HEARTBEAT_SECONDS',
    'INSTANCE_TTL_SECONDS',
    'SCHEDULER_LEASE_SECONDS',
    'EXCLUSIVE_OPERATION_LEASE_SECONDS',
    'WRITE_ACTIVITY_TTL_SECONDS',
    'INSTANCE_ID',
    'COOKIE_SECURE',
    'SCHEDULER_LEASE_NAME',
    'RESTORE_LEASE_NAME',
    'POLICY_ACTIVATION_LEASE_NAME',
]
